spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/campuscloud}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:campuscloud}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:campuscloud}
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false

recaptcha.secret=${RECAPTCHA_SECRET:}